version: '3.9'

services:
  react:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    ports:
      - "8080:8080"
    volumes:
      - ./frontend/src:/app/src
    env_file:
      - ./frontend/.env
    depends_on:
      - website
      - chat
      - mongo
    networks:
      - app-network
  
  website:
    build:
      context: ./website
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    env_file:
      - ./website/app/.env
    environment:
      - MONGODB_URI=mongodb://mongo:27017  # Reference the MongoDB 
    depends_on:
      - mongo
    networks:
      - app-network

  chat:
    build:
      context: ./chat
      dockerfile: Dockerfile
    ports:
      - "9000:9000"
    env_file:
      - ./chat/app/.env
    environment:
      - MONGODB_URI=mongodb://mongo:27017  # Reference the MongoDB 
    depends_on:
      - mongo
    networks:
      - app-network

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongo_user
      MONGO_INITDB_ROOT_PASSWORD: mongo_password
    volumes:
      - mongodb_data:/data/database
    networks:
      - app-network
    
volumes:
  mongodb_data:
    driver: local

networks:
  app-network:
    driver: bridge